/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2016-08-31 15:09:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.11.0.min.js\"></script>\t\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<p id=\"result2\"></p>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("         $.ajax({\r\n");
      out.write("             url : 'http://diadiem.com/Comp.aspx',\r\n");
      out.write("             type : 'POST',\r\n");
      out.write("             dataType : 'json',\r\n");
      out.write("             data: {\"stpe\":\"1\",\"st\":\"HaNoi\",\"F\":\"\",\"C\":\"\",\"K\":\"vlxd\",\"A\":\"0_0\",\"S\":\"M\",\"P\":\"1\",\"R\":\"2\",\"fD\":\"1\",\"uID\":\"0\",\"cID\":\"0\",\"dID\":\"0\"},\r\n");
      out.write("             success : function (result){\r\n");
      out.write("                 \r\n");
      out.write("                 var html = '';\r\n");
      out.write("                 html += '<table border=\"1\" cellspacing=\"0\" cellpadding=\"10\">';\r\n");
      out.write("                 html += '<tr>';\r\n");
      out.write("                    html += '<td>';\r\n");
      out.write("                         html += 'Dien thoai';\r\n");
      out.write("                         html += '</td>';\r\n");
      out.write("                         html += '<td>';\r\n");
      out.write("                         html += 'DiaChi';\r\n");
      out.write("                    html += '</td>';\r\n");
      out.write("                 html += '<tr>';\r\n");
      out.write("                var phone = new RegExp('^(0[129]).*');\r\n");
      out.write("                var text='';\r\n");
      out.write("                \r\n");
      out.write("                 // Káº¿t quáº£ lÃ  má»t object json\r\n");
      out.write("                 // NÃªn ta sáº½ loop result\r\n");
      out.write("                 $.each (result['dsCompany'], function (key, item){\r\n");
      out.write("                \t if( item['Add'] != '' && phone.test(item['P'])) {\r\n");
      out.write("\t                \t\t html +=  '<tr>';\r\n");
      out.write("\t                         html +=  '<td>';\r\n");
      out.write("\t                             html +=  item['P'];\r\n");
      out.write("\t                         html +=  '</td>';\r\n");
      out.write("\t                         html +=  '<td>';\r\n");
      out.write("\t                             html +=  item['Add'];\r\n");
      out.write("\t                         html +=  '</td>';\r\n");
      out.write("\t                     \thtml +=  '<tr>';\r\n");
      out.write("\t                     \ttext += item['P'] + \"&nbsp;\" + item['Add'] + \"<br/>\";\r\n");
      out.write("                \t }\r\n");
      out.write("                 });\r\n");
      out.write("                  \r\n");
      out.write("                 html +=  '</table>';\r\n");
      out.write("                  \r\n");
      out.write("                 $('#result2').html(html);\r\n");
      out.write("                 $('#result2').select();\r\n");
      out.write("                 document.execCommand(\"copy\");\r\n");
      out.write("             }\r\n");
      out.write("         });\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
